version: '3'
services:
  crypto-wallet-db:
    container_name: crypto-wallet-db
    image: postgres:12.13
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - crypto-wallet
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  crypto-wallet-api:
    container_name: crypto-wallet-api
    build:
      context: .
    depends_on:
      - crypto-wallet-db
    ports:
      - 8011:3000
    networks:
      - crypto-wallet
    env_file:
      - .env

volumes:
  dbdata:

networks:
  crypto-wallet:
